const healthTips = [
  // Physical (35+)
  {"tip": "Walk 30 minutes every day.", "category": "Physical"},
  {"tip": "Stretch for 10 minutes in the morning.", "category": "Physical"},
  {"tip": "Take the stairs instead of the elevator.", "category": "Physical"},
  {"tip": "Do strength training twice a week.", "category": "Physical"},
  {"tip": "Sleep 7-8 hours every night.", "category": "Physical"},
  {"tip": "Take short breaks during work to move around.", "category": "Physical"},
  {"tip": "Go for a brisk 10-minute walk after meals.", "category": "Physical"},
  {"tip": "Practice squats daily for stronger legs.", "category": "Physical"},
  {"tip": "Try jumping jacks for 5 minutes in the morning.", "category": "Physical"},
  {"tip": "Do desk stretches every hour.", "category": "Physical"},
  {"tip": "Try Tai Chi or gentle mobility exercises.", "category": "Physical"},
  {"tip": "Do yoga stretches in the morning.", "category": "Physical"},
  {"tip": "Take a walk in sunlight to boost vitamin D.", "category": "Physical"},
  {"tip": "Go swimming or cycling for cardio.", "category": "Physical"},
  {"tip": "Perform balance exercises to improve stability.", "category": "Physical"},
  {"tip": "Incorporate interval training in workouts.", "category": "Physical"},
  {"tip": "Do core-strengthening exercises.", "category": "Physical"},
  {"tip": "Engage in outdoor activities on weekends.", "category": "Physical"},
  {"tip": "Maintain good posture while sitting.", "category": "Physical"},
  {"tip": "Try Pilates to improve flexibility.", "category": "Physical"},
  {"tip": "Take short walks every hour during work.", "category": "Physical"},
  {"tip": "Practice deep breathing while stretching.", "category": "Physical"},
  {"tip": "Dance to your favorite music for 10 minutes.", "category": "Physical"},
  {"tip": "Do push-ups daily to strengthen upper body.", "category": "Physical"},
  {"tip": "Practice light jogging or brisk walking in morning.", "category": "Physical"},
  {"tip": "Do resistance band exercises at home.", "category": "Physical"},
  {"tip": "Perform lunges to strengthen legs and balance.", "category": "Physical"},
  {"tip": "Use a standing desk occasionally.", "category": "Physical"},
  {"tip": "Stretch hamstrings and back daily.", "category": "Physical"},
  {"tip": "Practice proper warm-up before exercises.", "category": "Physical"},
  {"tip": "Cool down and stretch after workouts.", "category": "Physical"},
  {"tip": "Try low-impact cardio like swimming or cycling.", "category": "Physical"},
  {"tip": "Engage in recreational sports weekly.", "category": "Physical"},
  {"tip": "Walk barefoot on grass occasionally for grounding.", "category": "Physical"},
  {"tip": "Alternate sitting and standing while working.", "category": "Physical"},

  // Mental (35+)
  {"tip": "Practice mindfulness for 10 minutes.", "category": "Mental"},
  {"tip": "Keep a gratitude journal daily.", "category": "Mental"},
  {"tip": "Meditate for 15 minutes to reduce stress.", "category": "Mental"},
  {"tip": "Spend some time in nature daily.", "category": "Mental"},
  {"tip": "Practice positive affirmations daily.", "category": "Mental"},
  {"tip": "Write down your goals and review them daily.", "category": "Mental"},
  {"tip": "Take a digital detox for 30 minutes daily.", "category": "Mental"},
  {"tip": "Visualize your goals each morning.", "category": "Mental"},
  {"tip": "Listen to relaxing nature sounds before sleep.", "category": "Mental"},
  {"tip": "Practice mindful breathing before sleep.", "category": "Mental"},
  {"tip": "Try meditation apps for guided sessions.", "category": "Mental"},
  {"tip": "Write down 3 things you are grateful for.", "category": "Mental"},
  {"tip": "Practice mindfulness while eating.", "category": "Mental"},
  {"tip": "Take a few moments for self-reflection daily.", "category": "Mental"},
  {"tip": "Read inspiring books to uplift your mood.", "category": "Mental"},
  {"tip": "Spend quality time with loved ones.", "category": "Mental"},
  {"tip": "Listen to calming music to reduce stress.", "category": "Mental"},
  {"tip": "Practice visualization techniques for motivation.", "category": "Mental"},
  {"tip": "Write down your thoughts in a journal.", "category": "Mental"},
  {"tip": "Practice deep breathing when feeling anxious.", "category": "Mental"},
  {"tip": "Take short mindfulness breaks during work.", "category": "Mental"},
  {"tip": "Focus on one task at a time for clarity.", "category": "Mental"},
  {"tip": "Practice gratitude before bedtime.", "category": "Mental"},
  {"tip": "Spend 10 minutes meditating after waking up.", "category": "Mental"},
  {"tip": "Engage in a hobby you enjoy.", "category": "Mental"},
  {"tip": "Smile more often to boost mood.", "category": "Mental"},
  {"tip": "Practice journaling to clear your mind.", "category": "Mental"},
  {"tip": "Limit social media consumption.", "category": "Mental"},
  {"tip": "Spend time with supportive friends.", "category": "Mental"},
  {"tip": "Use affirmations to start your day positively.", "category": "Mental"},
  {"tip": "Try mindfulness while walking or commuting.", "category": "Mental"},
  {"tip": "Visualize peaceful scenes for relaxation.", "category": "Mental"},
  {"tip": "Practice gratitude for small things daily.", "category": "Mental"},
  {"tip": "Engage in creative activities like drawing or writing.", "category": "Mental"},
  {"tip": "Take slow deep breaths when stressed.", "category": "Mental"},

  // Nutrition (35+)
  {"tip": "Drink at least 8 glasses of water daily.", "category": "Nutrition"},
  {"tip": "Eat more fruits and vegetables.", "category": "Nutrition"},
  {"tip": "Limit sugar intake to stay healthy.", "category": "Nutrition"},
  {"tip": "Include protein in every meal.", "category": "Nutrition"},
  {"tip": "Drink herbal teas instead of sugary drinks.", "category": "Nutrition"},
  {"tip": "Add fiber-rich foods to your diet.", "category": "Nutrition"},
  {"tip": "Avoid skipping breakfast.", "category": "Nutrition"},
  {"tip": "Snack on nuts and seeds instead of chips.", "category": "Nutrition"},
  {"tip": "Eat smaller meals more frequently.", "category": "Nutrition"},
  {"tip": "Include omega-3 rich foods in your diet.", "category": "Nutrition"},
  {"tip": "Reduce processed food consumption.", "category": "Nutrition"},
  {"tip": "Replace sugary snacks with fruits.", "category": "Nutrition"},
  {"tip": "Cook meals at home instead of eating out.", "category": "Nutrition"},
  {"tip": "Avoid eating late at night.", "category": "Nutrition"},
  {"tip": "Choose whole grains over refined grains.", "category": "Nutrition"},
  {"tip": "Eat seasonal fruits for better nutrition.", "category": "Nutrition"},
  {"tip": "Limit fast food to once a week.", "category": "Nutrition"},
  {"tip": "Include leafy greens in every meal.", "category": "Nutrition"},
  {"tip": "Swap sugary drinks for infused water.", "category": "Nutrition"},
  {"tip": "Include a source of fiber in breakfast.", "category": "Nutrition"},
  {"tip": "Balance carbs, proteins, and fats in meals.", "category": "Nutrition"},
  {"tip": "Avoid overeating and practice portion control.", "category": "Nutrition"},
  {"tip": "Add colorful vegetables to each meal.", "category": "Nutrition"},
  {"tip": "Limit fried food consumption.", "category": "Nutrition"},
  {"tip": "Avoid excessive caffeine intake.", "category": "Nutrition"},
  {"tip": "Include probiotic foods like yogurt.", "category": "Nutrition"},
  {"tip": "Snack on fruits instead of candy.", "category": "Nutrition"},
  {"tip": "Drink water before meals to aid digestion.", "category": "Nutrition"},
  {"tip": "Use healthy cooking oils like olive oil.", "category": "Nutrition"},
  {"tip": "Plan meals ahead to avoid junk food.", "category": "Nutrition"},
  {"tip": "Avoid skipping meals to maintain energy.", "category": "Nutrition"},
  {"tip": "Include nuts and seeds in snacks.", "category": "Nutrition"},
  {"tip": "Reduce salt intake for better heart health.", "category": "Nutrition"},
  {"tip": "Eat fermented foods for gut health.", "category": "Nutrition"}
];
